version: '3.9'
services:
  app:
    image: jenkins:lts-jdk11-docker
    build: .
    privileged: true
    restart: always
    ports: 
      - 8080:8080
      - 50000:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
